<h2>例外処理</h2>
プログラムを実行するにあたって、例外に対する処理は怠れませんよね、、、<br /><span class="cancel">面倒くさいからやりたくないですけどね、、、</span><br /><br />ということで、このページではエラーに対する処理について説明します。<br /><br />APIサーバという性質上、デフォルトで指定されているエラー用のJSONをそのまま使用しても特に問題ないですが、本番環境ではエラーに関する処理をより詳細に伝える必要性もありますからね、、、
<h2>FastAPIエラー</h2>
FastAPIは大きく以下の2つのエラーに大別できます。
<ul>
	<li>HTTPエラー</li>
	<li>FastAPIエラー</li>
</ul>
HTTPエラーとは、クライアントに送信するためのエラーです。<br />「404 Not Found」などが該当します。<br /><br />FastAPIエラーとはFastAPIを実行する際のエラーです。<br />例えば、整数型を指定している箇所に整数型に変換できないデータが格納されるなどの、いわゆるバリデーションエラーと呼ばれるものが該当します。
<h2>HTTPエラー</h2>
クライアントに送信するためのエラーで、HTTPExceptionと呼ばれます。<br />これはfastapiモジュールに含まれています。<br /><br />fastapiモジュールに含まれるHTTPException関数を使用します。
<code class="python">
	from fastapi import HTTPException
</code>
status_codeにステータスコードを、detailにエラーメッセージを指定します。<br /><br />では、「/error」というパスに対するアクセスに対して、エラーコード「444」を返してみましょう♪
<code class="python">
	@app.get("/error")
	async def read_root():
		raise HTTPException(status_code=444, detail="I am an error!!!")
		return PlainTextResponse("ex")
</code>
<img src="/static/img/S00/0103/fastapi_http_exeption.gif" alt="HTTPエラー" />
<h2>FastAPIエラー</h2>
FastAPIエラーはさらに以下の2つの分類されます。<br />開発者モードの下に表示されているアレですね、、、
<img src="/static/img/S00/0103/fastapi_schemas.png" alt="FastAPIスキーマ" />
<ul>
	<li>HTTPValidationError</li>
	<li>ValidationError</li>
</ul>
<h3>RequestValidationError</h3>

<code class="python">
	from fastapi.exceptions import RequestValidationError

	@app.exception_handler(RequestValidationError)
	def validation_exception_handler(_a, _b):
		return FileResponse(g.WWWROOT + "html/error/404.html")
</code>



<h2>HTTPValidationError</h2>

